### ISSUE TITLE
[bug] Check does not fail when number of invalidations increases

### ISSUE THREAD

**Issue by LilithHafner** [julia-actions/julia-invalidations#16]
https://github.com/JuliaCollections/SortingAlgorithms.jl/pull/61

<img width="1459" alt="Screenshot 2023-10-18 at 8 43 05 AM" src="https://github.com/julia-actions/julia-invalidations/assets/60898866/9f0fc7b5-4eaf-4218-80bd-542d9cd15e90">

**Comment by LilithHafner** [comment]
.yml file: https://github.com/JuliaCollections/SortingAlgorithms.jl/blob/ab7106bf8d25c5d784451cde59e8eef95687a16d/.github/workflows/Invalidations.yml

**Comment by KristofferC** [comment]
And here the checks fail when the number of invalidations got reduced:

https://github.com/JuliaStrings/InlineStrings.jl/pull/77

<img width="766" alt="image" src="https://github.com/user-attachments/assets/33607bc9-916c-4e72-bcd1-bee4a41460eb">

I'm quite sure the issue is that in the

```
      if: steps.invs_pr.outputs.total > steps.invs_default.outputs.total
      run: exit 1
```

line of the script the comparison is a string comparison and not a numerical comparison.

I am not sure this check has ever worked...
